### ISSUE TITLE
可以实现节点正则匹配？

### ISSUE THREAD

**Issue by RikkaBlue** [SukkaW/ClashEditor#2]
如题，在策略组里面增加筛选节点的功能，批量添加。
可能正则有一点的门槛，前端实现关键字搜索，我觉得也是会很好用的。
不知道能否实现。

**Comment by SukkaW** [comment]
如果只是单纯搜索节点，你可以用 <kbd>ctrl</kbd> + <kbd>F</kbd>

**Comment by nb5p** [comment]
> 如果只是单纯搜索节点，你可以用 ctrl + F

我觉得你明白他的想要的功能
