### ISSUE TITLE
添加显示“Rule 中使用了不存在的 Proxy Group”的具体Group

### ISSUE THREAD

**Issue by HinataKato** [SukkaW/ClashEditor#7]
如题，我查了半天都没查出来那有问题

**Comment by zanyatta** [comment]
你在使用 ClashX吗？我也遇到了这个问题。解决问题的办法很简单：
手动将配置中的 Proxy 替换为 proxies，将 Proxy Group 替换为 proxy-groups，将 Rule 替换为 rules

**Comment by HinataKato** [comment]
> 你在使用 ClashX吗？我也遇到了这个问题。解决问题的办法很简单：
> 手动将配置中的 Proxy 替换为 proxies，将 Proxy Group 替换为 proxy-groups，将 Rule 替换为 rules

我也忘了 大概率我自己问题
